ARTICULOS_EXPLICACION = {
    "RobberyReport": "Delito de robo",
    "Article240_1": "Artículo 240.1: Robo con forzamiento.",
    "Article240_2_1_1-5": "Artículo 240.2.1.1a5: Robo con forzamiento con bienes con característica especial.",
    "Article240_2_1_6": "Artículo 240.2.1.6: Robo con forzamiento con afectaciones graves a la víctima.",
    "Article240_2_1_7": "Artículo 240.2.1.7: Robo con forzamiento con acusado con más de 3 condenas previas.",
    "Article240_2_1_8": "Artículo 240.2.1.8: Robo con forzamiento con cómplices menores de edad.",
    "Article240_2_1_9": "Artículo 240.2.1.9: Robo con forzamiento con pertenencia a organización criminal.",
    "Article240_2_2": "Artículo 240.2.2: Robo con forzamiento con bienes con más de una característica especial.",
    "Article241_1": "Artículo 241.1: Robo con allanamiento de casa o local.",
    "Article241_4": "Artículo 241.4: Robo con allanamiento con daños graves.",
    "Article241_4_1_1-5": "Artículo 241.4.1.1a5: Robo con allanamiento con bienes con característica especial.",
    "Article241_4_1_6": "Artículo 241.4.1.6: Robo con allanamiento con afectaciones graves a la víctima.",
    "Article241_4_1_7": "Artículo 241.4.1.7: Robo con allanamiento con acusado con más de 3 condenas previas.",
    "Article241_4_1_8": "Artículo 241.4.1.8: Robo con allanamiento con cómplices menores de edad.",
    "Article241_4_1_9": "Artículo 241.4.1.9: Robo con allanamiento con pertenencia a organización criminal.",
    "Article241_4_2": "Artículo 241.4.2: Robo con allanamiento con bienes con más de una característica especial.",
    "Article242": "Artículo 242: Robo con violencia o intimidación.",
    "Article242_2": "Artículo 242.2: Robo con violencia o intimidación y allanamiento de casa o local.",
    "Article242_2_3": "Artículo 242.2.3: Robo con violencia o intimidación y allanamiento con uso de armas.",
    "Article242_2_4": "Artículo 242.2.4: Robo con violencia o intimidación y allanamiento con uso de violencia mínima.",
    "Article242_3": "Artículo 242.3: Robo con violencia o intimidación y uso de armas.",
    "Article242_4": "Artículo 242.4: Robo con violencia o intimidación y uso de violencia mínima.",
    "TheftReport": "Delito de hurto",
    "TheftByNotOwner": "Hurto por parte de no propietario",
    "Article234_1": "Artículo 234.1: Hurto por parte de no propietario con valor económico superior a 400€.",
    "Article234_2": "Artículo 234.2: Hurto por parte de no propietario con valor económico inferior o igual a 400€.",
    "Article234_3": "Artículo 234.3: Hurto por parte de no propietario con neutralización, eliminación o inutilización de medidas de seguridad.",
    "Article235_1_1-5": "Artículo 235.1.1a5: Hurto por parte de no propietario con bienes con característica especial.",
    "Article235_1_6": "Artículo 235.1.6: Hurto por parte de no propietario con afectaciones graves a la víctima.",
    "Article235_1_7": "Artículo 235.1.7: Hurto por parte de no propietario con acusado con más de 3 condenas previas.",
    "Article235_1_8": "Artículo 235.1.8: Hurto por parte de no propietario con cómplices menores de edad.",
    "Article235_1_9": "Artículo 235.1.9: Hurto por parte de no propietario con pertenencia a organización criminal.",
    "Article235_2": "Artículo 235.2: Hurto por parte de no propietario con bienes con más de una característica especial.",
    "TheftByOwner": "Hurto por parte de propietario",
    "Article236_1": "Artículo 236.1: Hurto por parte de propietario con valor económico superior a 400€.",
    "Article236_2": "Artículo 236.2: Hurto por parte de propietario con valor económico inferior o igual a 400€.",
}
